#pragma once

#include <regex>
#include <boost/filesystem.hpp>

namespace fs = boost::filesystem;


namespace bu {
    /*
    * Helper class detecting various file types generated by BU
    */
    struct File {
        static inline bool isEoR(const std::string& file) {
            return file.find("_EoR.jsn") != std::string::npos;
        }
        static inline bool isEoLS(const std::string& file) {
            return file.find("_EoLS.jsn") != std::string::npos;  
        }
    };

    fs::path getRunDirectory(int runNumber);

    typedef std::vector<std::string> files_t;
    
    files_t getFilesInRunDirectory(const std::string& runDirectory);
}
